# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2020-04-06 01:13:07
"""
import arcpy
from sys import argv


def Step6EliminatePolygonPart(Output_Buffer, Output_Finished, Condition="AREA", Area="0 Unknown", Percentage=0,
                              Eliminate_contained_parts_only=True):  # Step6EliminatePolygonPart

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Process: Eliminate Polygon Part (Eliminate Polygon Part)
    arcpy.EliminatePolygonPart_management(in_features=Output_Buffer, out_feature_class=Output_Finished,
                                          condition=Condition, part_area=Area, part_area_percent=Percentage,
                                          part_option=Eliminate_contained_parts_only)


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(
            scratchWorkspace=r"C:\Users\kjuli\PycharmProjects\USGS_Geostatistics\USGS_Geostatistics\USGS_Geostatistics.gdb",
            workspace=r"C:\Users\kjuli\PycharmProjects\USGS_Geostatistics\USGS_Geostatistics\USGS_Geostatistics.gdb"):
        Step6EliminatePolygonPart(*argv[1:])
