# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2020-04-06 01:13:07
"""
import arcpy
from sys import argv


def Step4SmoothPolygon(Input_Barrier_Layers_2_, Smoothing_Tolerance, Output_Simplify, Output_Smooth,
                       Smoothing_Algorithm="PAEK", Preserve_endpoint_for_rings=True,
                       Handling_Topological_Errors_2_="NO_CHECK"):  # Step4SmoothPolygon

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Process: Smooth Polygon (Smooth Polygon)
    arcpy.SmoothPolygon_cartography(in_features=Output_Simplify, out_feature_class=Output_Smooth,
                                    algorithm=Smoothing_Algorithm, tolerance=Smoothing_Tolerance,
                                    endpoint_option=Preserve_endpoint_for_rings,
                                    error_option=Handling_Topological_Errors_2_, in_barriers=Input_Barrier_Layers_2_)


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(
            scratchWorkspace=r"C:\Users\kjuli\PycharmProjects\USGS_Geostatistics\USGS_Geostatistics\USGS_Geostatistics.gdb",
            workspace=r"C:\Users\kjuli\PycharmProjects\USGS_Geostatistics\USGS_Geostatistics\USGS_Geostatistics.gdb"):
        Step4SmoothPolygon(*argv[1:])
