# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2020-04-06 01:13:07
"""
import arcpy
from sys import argv


def Step2AggregatePolygons(Aggregation_Distance, Barrier_Features, Output_Singlepart, Output_Aggregate,
                           Minimum_Area="0 Unknown", Minimum_Hole_Size="0 Unknown",
                           Preserve_orthogonal_shape=False):  # Step2AggregatePolygons

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Process: Aggregate Polygons (Aggregate Polygons)
    arcpy.AggregatePolygons_cartography(in_features=Output_Singlepart, out_feature_class=Output_Aggregate,
                                        aggregation_distance=Aggregation_Distance, minimum_area=Minimum_Area,
                                        minimum_hole_size=Minimum_Hole_Size,
                                        orthogonality_option=Preserve_orthogonal_shape,
                                        barrier_features=Barrier_Features, out_table=Output_Table)


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(
            scratchWorkspace=r"C:\Users\kjuli\PycharmProjects\USGS_Geostatistics\USGS_Geostatistics\USGS_Geostatistics.gdb",
            workspace=r"C:\Users\kjuli\PycharmProjects\USGS_Geostatistics\USGS_Geostatistics\USGS_Geostatistics.gdb"):
        Step2AggregatePolygons(*argv[1:])
