# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2020-04-07 00:16:16
"""
import arcpy
from sys import argv


def Overview(Input_Geologic_Features, Output_Finished, Aggregation_Distance, Minimum_Area="0 Unknown",
             Minimum_Hole_Size="0 Unknown", Preserve_orthogonal_shape=False, Barrier_Features,
             Simplification_Algorithm="POINT_REMOVE", Simplification_Tolerance, Minimum_Area_2_="0 Unknown",
             Handling_Topological_Errors="RESOLVE_ERRORS", Keep_collapsed_points=True, Input_Barrier_Layers,
             Smoothing_Algorithm="PAEK", Smoothing_Tolerance, Preserve_endpoint_for_rings=True,
             Handling_Topological_Errors_2_="NO_CHECK", Input_Barrier_Layers_2_, Distance_value_or_field_,
             Side_Type="FULL", End_Type="ROUND", Dissolve_Type="NONE", Dissolve_Field_s_, Method="PLANAR",
             Condition="AREA", Area="0 Unknown", Percentage=0, Eliminate_contained_parts_only=True):  # Overview

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Process: Union (Union)
    Output_Union = ""
    arcpy.Union_analysis(in_features=Input_Geologic_Features, out_feature_class=Output_Union, join_attributes="ALL",
                         cluster_tolerance="", gaps="GAPS")

    # Process: Multipart To Singlepart (Multipart To Singlepart) 
    Output_Singlepart = ""
    arcpy.MultipartToSinglepart_management(in_features=Output_Union, out_feature_class=Output_Singlepart)

    # Process: Aggregate Polygons (Aggregate Polygons) 
    Output_Aggregate = ""
    arcpy.AggregatePolygons_cartography(in_features=Output_Singlepart, out_feature_class=Output_Aggregate,
                                        aggregation_distance=Aggregation_Distance, minimum_area=Minimum_Area,
                                        minimum_hole_size=Minimum_Hole_Size,
                                        orthogonality_option=Preserve_orthogonal_shape,
                                        barrier_features=Barrier_Features, out_table=Output_Table)

    # Process: Simplify Polygon (Simplify Polygon) 
    Output_Simplify = ""
    output_feature_class_Pnt = \
    arcpy.SimplifyPolygon_cartography(in_features=Output_Aggregate, out_feature_class=Output_Simplify,
                                      algorithm=Simplification_Algorithm, tolerance=Simplification_Tolerance,
                                      minimum_area=Minimum_Area_2_, error_option=Handling_Topological_Errors,
                                      collapsed_point_option=Keep_collapsed_points, in_barriers=Input_Barrier_Layers)[0]

    # Process: Smooth Polygon (Smooth Polygon) 
    Output_Smooth = ""
    arcpy.SmoothPolygon_cartography(in_features=Output_Simplify, out_feature_class=Output_Smooth,
                                    algorithm=Smoothing_Algorithm, tolerance=Smoothing_Tolerance,
                                    endpoint_option=Preserve_endpoint_for_rings,
                                    error_option=Handling_Topological_Errors_2_, in_barriers=Input_Barrier_Layers_2_)

    # Process: Buffer (Buffer) 
    Output_Buffer = ""
    arcpy.Buffer_analysis(in_features=Output_Smooth, out_feature_class=Output_Buffer,
                          buffer_distance_or_field=Distance_value_or_field_, line_side=Side_Type,
                          line_end_type=End_Type, dissolve_option=Dissolve_Type, dissolve_field=Dissolve_Field_s_,
                          method=Method)

    # Process: Eliminate Polygon Part (Eliminate Polygon Part) 
    arcpy.EliminatePolygonPart_management(in_features=Output_Buffer, out_feature_class=Output_Finished,
                                          condition=Condition, part_area=Area, part_area_percent=Percentage,
                                          part_option=Eliminate_contained_parts_only)


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(
            scratchWorkspace=r"C:\Users\kjuli\PycharmProjects\USGS_Geostatistics\USGS_Geostatistics\USGS_Geostatistics.gdb",
            workspace=r"C:\Users\kjuli\PycharmProjects\USGS_Geostatistics\USGS_Geostatistics\USGS_Geostatistics.gdb"):
        Overview(*argv[1:])
