# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2020-04-06 01:13:07
"""
from Prototract.USGS_Geostatistics.Step1Input import Step1Input
from Prototract.USGS_Geostatistics.Step2AggregatePolygons import Step2AggregatePolygons
from Prototract.USGS_Geostatistics.Step3SimplifyPolygon import Step3SimplifyPolygon
from Prototract.USGS_Geostatistics.Step4SmoothPolygon import Step4SmoothPolygon
from Prototract.USGS_Geostatistics.Step5Buffer import Step5Buffer
from Prototract.USGS_Geostatistics.Step6EliminatePolygonPart import Step6EliminatePolygonPart
import arcpy


def Prototract():  # Prototract

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Process: Step1Input (Step1Input)
    Output_Singlepart = ""
    Step1Input(Input_Geologic_Features=[], Output_Singlepart=Output_Singlepart)

    # Process: Step2AggregatePolygons (Step2AggregatePolygons) 
    Output_Aggregate = ""
    Step2AggregatePolygons(Aggregation_Distance="", Barrier_Features=[], Output_Singlepart=Output_Singlepart,
                           Output_Aggregate=Output_Aggregate, Minimum_Area="0 Unknown", Minimum_Hole_Size="0 Unknown",
                           Preserve_orthogonal_shape="NON_ORTHOGONAL")

    # Process: Step3SimplifyPolygon (Step3SimplifyPolygon) 
    Output_Simplify = ""
    Step3SimplifyPolygon(Simplification_Tolerance="", Input_Barrier_Layers=[], Output_Aggregate=Output_Aggregate,
                         Output_Simplify=Output_Simplify, Simplification_Algorithm="POINT_REMOVE",
                         Minimum_Area__2_="0 Unknown", Handling_Topological_Errors="RESOLVE_ERRORS",
                         Keep_collapsed_points="KEEP_COLLAPSED_POINTS")

    # Process: Step4SmoothPolygon (Step4SmoothPolygon) 
    Output_Smooth = ""
    Step4SmoothPolygon(Input_Barrier_Layers__2_=[], Smoothing_Tolerance="", Output_Simplify=Output_Simplify,
                       Output_Smooth=Output_Smooth, Smoothing_Algorithm="PAEK",
                       Preserve_endpoint_for_rings="FIXED_ENDPOINT", Handling_Topological_Errors__2_="NO_CHECK")

    # Process: Step5Buffer (Step5Buffer) 
    Output_Buffer = ""
    Step5Buffer(Distance__value_or_field_="", Dissolve_Field_s_=[], Output_Smooth=Output_Smooth,
                Output_Buffer=Output_Buffer, Side_Type="FULL", End_Type="ROUND", Dissolve_Type="NONE", Method="PLANAR")

    # Process: Step6EliminatePolygonPart (Step6EliminatePolygonPart) 
    Output_Finished = ""
    Step6EliminatePolygonPart(Output_Buffer=Output_Buffer, Output_Finished=Output_Finished, Condition="AREA",
                              Area="0 Unknown", Percentage=0, Eliminate_contained_parts_only="CONTAINED_ONLY")


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(
            scratchWorkspace=r"C:\Users\kjuli\PycharmProjects\USGS_Geostatistics\USGS_Geostatistics\USGS_Geostatistics.gdb",
            workspace=r"C:\Users\kjuli\PycharmProjects\USGS_Geostatistics\USGS_Geostatistics\USGS_Geostatistics.gdb"):
        Prototract()
