# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2020-04-05 23:25:23
"""
import arcpy
from sys import argv

def Step4-SmoothPolygon(Smoothing_Algorithm="PAEK", Smoothing_Tolerance, Preserve_endpoint_for_rings=True, Handling_Topological_Errors_2_="NO_CHECK", Input_Barrier_Layers_2_, Output_Smooth, Output_Simplify):  # Step 4 - Smooth Polygon

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False


    # Process: Smooth Polygon (Smooth Polygon) 
    arcpy.SmoothPolygon_cartography(in_features=Output_Simplify, out_feature_class=Output_Smooth, algorithm=Smoothing_Algorithm, tolerance=Smoothing_Tolerance, endpoint_option=Preserve_endpoint_for_rings, error_option=Handling_Topological_Errors_2_, in_barriers=Input_Barrier_Layers_2_)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\kjuli\PycharmProjects\USGS_Geostatistics\USGS_Geostatistics\USGS_Geostatistics.gdb", workspace=r"C:\Users\kjuli\PycharmProjects\USGS_Geostatistics\USGS_Geostatistics\USGS_Geostatistics.gdb"):
        Step4-SmoothPolygon(*argv[1:])
