# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2020-04-05 23:25:23
"""
import arcpy
from sys import argv

def Step1-Input(Input_Geologic_Features, Output_Singlepart):  # Step 1 - Input

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False


    # Process: Union (Union) 
    Output_Union = ""
    arcpy.Union_analysis(in_features=Input_Geologic_Features, out_feature_class=Output_Union, join_attributes="ALL", cluster_tolerance="", gaps="GAPS")

    # Process: Multipart To Singlepart (Multipart To Singlepart) 
    arcpy.MultipartToSinglepart_management(in_features=Output_Union, out_feature_class=Output_Singlepart)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\kjuli\PycharmProjects\USGS_Geostatistics\USGS_Geostatistics\USGS_Geostatistics.gdb", workspace=r"C:\Users\kjuli\PycharmProjects\USGS_Geostatistics\USGS_Geostatistics\USGS_Geostatistics.gdb"):
        Step1-Input(*argv[1:])
