# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2020-04-05 23:25:23
"""
import arcpy
from sys import argv

def Step5-Buffer(Distance_value_or_field_, Side_Type="FULL", End_Type="ROUND", Dissolve_Type="NONE", Dissolve_Field_s_, Method="PLANAR", Output_Buffer, Output_Smooth):  # Step 5 - Buffer

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False


    # Process: Buffer (Buffer) 
    arcpy.Buffer_analysis(in_features=Output_Smooth, out_feature_class=Output_Buffer, buffer_distance_or_field=Distance_value_or_field_, line_side=Side_Type, line_end_type=End_Type, dissolve_option=Dissolve_Type, dissolve_field=Dissolve_Field_s_, method=Method)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\kjuli\PycharmProjects\USGS_Geostatistics\USGS_Geostatistics\USGS_Geostatistics.gdb", workspace=r"C:\Users\kjuli\PycharmProjects\USGS_Geostatistics\USGS_Geostatistics\USGS_Geostatistics.gdb"):
        Step5-Buffer(*argv[1:])
