# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2020-04-05 23:25:23
"""
import arcpy
from sys import argv

def Step6-EliminatePolygonPart(Output_Finished, Condition="AREA", Area="0 Unknown", Percentage=0, Eliminate_contained_parts_only=True, Output_Buffer):  # Step 6 - Eliminate Polygon Part

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False


    # Process: Eliminate Polygon Part (Eliminate Polygon Part) 
    arcpy.EliminatePolygonPart_management(in_features=Output_Buffer, out_feature_class=Output_Finished, condition=Condition, part_area=Area, part_area_percent=Percentage, part_option=Eliminate_contained_parts_only)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\kjuli\PycharmProjects\USGS_Geostatistics\USGS_Geostatistics\USGS_Geostatistics.gdb", workspace=r"C:\Users\kjuli\PycharmProjects\USGS_Geostatistics\USGS_Geostatistics\USGS_Geostatistics.gdb"):
        Step6-EliminatePolygonPart(*argv[1:])
