# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2020-04-05 23:25:23
"""
from USGSGeostatistics.Step1-Input import Step1-Input
from USGSGeostatistics.Step2-AggregatePolygons import Step2-AggregatePolygons
from USGSGeostatistics.Step3-SimplifyPolygon import Step3-SimplifyPolygon
from USGSGeostatistics.Step4-SmoothPolygon import Step4-SmoothPolygon
from USGSGeostatistics.Step5-Buffer import Step5-Buffer
from USGSGeostatistics.Step6-EliminatePolygonPart import Step6-EliminatePolygonPart
import arcpy

def Model():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    Input_Geologic_Features = []

    # Process: Step 1 - Input (Step 1 - Input) 
    Output_Singlepart = ""
    Step1-Input(Input_Geologic_Features=Input_Geologic_Features, Output_Singlepart=Output_Singlepart)

    # Process: Step 2 - Aggregate Polygons (Step 2 - Aggregate Polygons) 
    Output_Aggregate = ""
    Step2-AggregatePolygons(Aggregation_Distance="", Minimum_Area="0 Unknown", Minimum_Hole_Size="0 Unknown", Preserve_orthogonal_shape="NON_ORTHOGONAL", Barrier_Features=[], Output_Singlepart=Output_Singlepart, Output_Aggregate=Output_Aggregate)

    # Process: Step 3 - Simplify Polygon (Step 3 - Simplify Polygon) 
    Output_Simplify = ""
    Step3-SimplifyPolygon(Simplification_Algorithm="POINT_REMOVE", Simplification_Tolerance="", Minimum_Area__2_="0 Unknown", Handling_Topological_Errors="RESOLVE_ERRORS", Keep_collapsed_points="KEEP_COLLAPSED_POINTS", Input_Barrier_Layers=[], Output_Aggregate=Output_Aggregate, Output_Simplify=Output_Simplify)

    # Process: Step 4 - Smooth Polygon (Step 4 - Smooth Polygon) 
    Output_Smooth = ""
    Step4-SmoothPolygon(Smoothing_Algorithm="PAEK", Smoothing_Tolerance="", Preserve_endpoint_for_rings="FIXED_ENDPOINT", Handling_Topological_Errors__2_="NO_CHECK", Input_Barrier_Layers__2_=[], Output_Smooth=Output_Smooth, Output_Simplify=Output_Simplify)

    # Process: Step 5 - Buffer (Step 5 - Buffer) 
    Output_Buffer = ""
    Step5-Buffer(Distance__value_or_field_="", Side_Type="FULL", End_Type="ROUND", Dissolve_Type="NONE", Dissolve_Field_s_=[], Method="PLANAR", Output_Buffer=Output_Buffer, Output_Smooth=Output_Smooth)

    # Process: Step 6 - Eliminate Polygon Part (Step 6 - Eliminate Polygon Part) 
    Step6-EliminatePolygonPart(Output_Finished=Output_Finished, Condition="AREA", Area="0 Unknown", Percentage=0, Eliminate_contained_parts_only="CONTAINED_ONLY", Output_Buffer=Output_Buffer)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\kjuli\PycharmProjects\USGS_Geostatistics\USGS_Geostatistics\USGS_Geostatistics.gdb", workspace=r"C:\Users\kjuli\PycharmProjects\USGS_Geostatistics\USGS_Geostatistics\USGS_Geostatistics.gdb"):
        Model()
